// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAohPBqrmcGnBUCqITX4uT741SraJRfIwk',
    appId: '1:1028159410058:android:20f10a9c83c00556ee8273',
    messagingSenderId: '1028159410058',
    projectId: 'task-two-53c0e',
    storageBucket: 'task-two-53c0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiDakRj7oS1Mp0XkTfYsuttmtqHTcqb3o',
    appId: '1:1028159410058:ios:67045eda5b9674bbee8273',
    messagingSenderId: '1028159410058',
    projectId: 'task-two-53c0e',
    storageBucket: 'task-two-53c0e.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiDakRj7oS1Mp0XkTfYsuttmtqHTcqb3o',
    appId: '1:1028159410058:ios:67045eda5b9674bbee8273',
    messagingSenderId: '1028159410058',
    projectId: 'task-two-53c0e',
    storageBucket: 'task-two-53c0e.appspot.com',
    iosBundleId: 'com.example.task',
  );

}